// ════════════════════════════════════════════════════
// DATA.JS — All Vedic Astrology Constants
// ════════════════════════════════════════════════════

const DATA = {

  rashis: [
    { name: 'Aries',       hi: 'मेष',    lord: 2, elem: 'Fire',  quality: 'Cardinal', symbol: '♈' },
    { name: 'Taurus',      hi: 'वृषभ',   lord: 5, elem: 'Earth', quality: 'Fixed',    symbol: '♉' },
    { name: 'Gemini',      hi: 'मिथुन',  lord: 3, elem: 'Air',   quality: 'Mutable',  symbol: '♊' },
    { name: 'Cancer',      hi: 'कर्क',   lord: 1, elem: 'Water', quality: 'Cardinal', symbol: '♋' },
    { name: 'Leo',         hi: 'सिंह',   lord: 0, elem: 'Fire',  quality: 'Fixed',    symbol: '♌' },
    { name: 'Virgo',       hi: 'कन्या',  lord: 3, elem: 'Earth', quality: 'Mutable',  symbol: '♍' },
    { name: 'Libra',       hi: 'तुला',   lord: 5, elem: 'Air',   quality: 'Cardinal', symbol: '♎' },
    { name: 'Scorpio',     hi: 'वृश्चिक',lord: 2, elem: 'Water', quality: 'Fixed',    symbol: '♏' },
    { name: 'Sagittarius', hi: 'धनु',    lord: 4, elem: 'Fire',  quality: 'Mutable',  symbol: '♐' },
    { name: 'Capricorn',   hi: 'मकर',   lord: 6, elem: 'Earth', quality: 'Cardinal', symbol: '♑' },
    { name: 'Aquarius',    hi: 'कुम्भ',  lord: 6, elem: 'Air',   quality: 'Fixed',    symbol: '♒' },
    { name: 'Pisces',      hi: 'मीन',   lord: 4, elem: 'Water', quality: 'Mutable',  symbol: '♓' },
  ],

  planets: [
    { id: 0, name: 'Sun',     hi: 'सूर्य',  sym: '☉', en: 'Surya',      nature: 'malefic', color: '#ff8c00', bg: '#fff3e0', dasha: 6,  exalt: 0,  debit: 6,  own: [4],      gem: 'Ruby',             day: 'Sunday' },
    { id: 1, name: 'Moon',    hi: 'चंद्र',  sym: '☽', en: 'Chandra',     nature: 'benefic', color: '#4a90d9', bg: '#e8f4fd', dasha: 10, exalt: 1,  debit: 7,  own: [3],      gem: 'Pearl',            day: 'Monday' },
    { id: 2, name: 'Mars',    hi: 'मंगल',   sym: '♂', en: 'Mangal',      nature: 'malefic', color: '#e53935', bg: '#fde8e8', dasha: 7,  exalt: 9,  debit: 3,  own: [0, 7],   gem: 'Red Coral',        day: 'Tuesday' },
    { id: 3, name: 'Mercury', hi: 'बुध',    sym: '☿', en: 'Budha',       nature: 'neutral', color: '#43a047', bg: '#e8f5e9', dasha: 17, exalt: 5,  debit: 11, own: [2, 5],   gem: 'Emerald',          day: 'Wednesday' },
    { id: 4, name: 'Jupiter', hi: 'गुरु',   sym: '♃', en: 'Brihaspati',  nature: 'benefic', color: '#f9a825', bg: '#fffde7', dasha: 16, exalt: 3,  debit: 9,  own: [8, 11],  gem: 'Yellow Sapphire',  day: 'Thursday' },
    { id: 5, name: 'Venus',   hi: 'शुक्र',  sym: '♀', en: 'Shukra',      nature: 'benefic', color: '#e91e8c', bg: '#fce4ec', dasha: 20, exalt: 11, debit: 5,  own: [1, 6],   gem: 'Diamond',          day: 'Friday' },
    { id: 6, name: 'Saturn',  hi: 'शनि',    sym: '♄', en: 'Shani',       nature: 'malefic', color: '#5c6bc0', bg: '#ede7f6', dasha: 19, exalt: 6,  debit: 0,  own: [9, 10],  gem: 'Blue Sapphire',    day: 'Saturday' },
    { id: 7, name: 'Rahu',    hi: 'राहु',   sym: '☊', en: 'Rahu',        nature: 'malefic', color: '#7b1fa2', bg: '#f3e5f5', dasha: 18, exalt: 1,  debit: 7,  own: [],       gem: 'Hessonite',        day: 'Saturday' },
    { id: 8, name: 'Ketu',    hi: 'केतु',   sym: '☋', en: 'Ketu',        nature: 'malefic', color: '#00695c', bg: '#e0f2f1', dasha: 7,  exalt: 7,  debit: 1,  own: [],       gem: "Cat's Eye",        day: 'Tuesday' },
  ],

  houses: [
    { num: 1,  name: 'Tanu',     hi: 'तनु',    full: 'Lagna / Self',            meaning: 'Physical appearance, personality, health, self-expression, beginnings' },
    { num: 2,  name: 'Dhana',    hi: 'धन',     full: 'Wealth & Family',         meaning: 'Money, speech, food, family, accumulated wealth, early education' },
    { num: 3,  name: 'Sahaj',    hi: 'सहज',    full: 'Siblings & Courage',      meaning: 'Brothers, sisters, courage, communication, short journeys, skills' },
    { num: 4,  name: 'Bandhu',   hi: 'बंधु',   full: 'Home & Mother',           meaning: 'Home, mother, property, land, emotional security, domestic life' },
    { num: 5,  name: 'Putra',    hi: 'पुत्र',  full: 'Children & Intelligence', meaning: 'Children, intelligence, creativity, romance, education, past merit' },
    { num: 6,  name: 'Shatru',   hi: 'शत्रु',  full: 'Enemies & Service',       meaning: 'Enemies, diseases, debts, service, daily work, obstacles to overcome' },
    { num: 7,  name: 'Kalatra',  hi: 'कलत्र',  full: 'Marriage & Partnership',  meaning: 'Spouse, marriage, business partners, open enemies, foreign travel' },
    { num: 8,  name: 'Mrityu',   hi: 'मृत्यु', full: 'Transformation & Death',  meaning: 'Longevity, occult, sudden events, inheritance, surgery, secrets' },
    { num: 9,  name: 'Dharma',   hi: 'धर्म',   full: 'Luck & Dharma',           meaning: 'Fortune, father, religion, guru, long journeys, higher education, grace' },
    { num: 10, name: 'Karma',    hi: 'कर्म',   full: 'Career & Status',         meaning: 'Profession, status, authority, father, public image, karma, government' },
    { num: 11, name: 'Labha',    hi: 'लाभ',    full: 'Gains & Desires',         meaning: 'Income, gains, elder siblings, hopes, friends, fulfillment of desires' },
    { num: 12, name: 'Vyaya',    hi: 'व्यय',   full: 'Loss & Liberation',       meaning: 'Expenses, losses, foreign lands, spirituality, isolation, final liberation' },
  ],

  // North Indian chart: fixed house positions in 4x4 grid cell coords → house number
  northMap: {
    '0,0': 12, '0,1': 1,  '0,2': 2,  '0,3': 3,
    '1,0': 11,                         '1,3': 4,
    '2,0': 10,                         '2,3': 5,
    '3,0': 9,  '3,1': 8,  '3,2': 7,  '3,3': 6,
  },

  nakshatras: [
    { name: 'Ashwini',          lord: 8, deity: 'Ashwini Kumaras' },
    { name: 'Bharani',          lord: 5, deity: 'Yama' },
    { name: 'Krittika',         lord: 0, deity: 'Agni' },
    { name: 'Rohini',           lord: 1, deity: 'Brahma' },
    { name: 'Mrigashira',       lord: 2, deity: 'Soma' },
    { name: 'Ardra',            lord: 7, deity: 'Rudra' },
    { name: 'Punarvasu',        lord: 4, deity: 'Aditi' },
    { name: 'Pushya',           lord: 6, deity: 'Brihaspati' },
    { name: 'Ashlesha',         lord: 3, deity: 'Nagas' },
    { name: 'Magha',            lord: 8, deity: 'Pitrus' },
    { name: 'Purva Phalguni',   lord: 5, deity: 'Bhaga' },
    { name: 'Uttara Phalguni',  lord: 0, deity: 'Aryaman' },
    { name: 'Hasta',            lord: 1, deity: 'Savitar' },
    { name: 'Chitra',           lord: 2, deity: 'Vishwakarma' },
    { name: 'Swati',            lord: 7, deity: 'Vayu' },
    { name: 'Vishakha',         lord: 4, deity: 'Indra-Agni' },
    { name: 'Anuradha',         lord: 6, deity: 'Mitra' },
    { name: 'Jyeshtha',         lord: 3, deity: 'Indra' },
    { name: 'Mula',             lord: 8, deity: 'Nirrti' },
    { name: 'Purva Ashadha',    lord: 5, deity: 'Apas' },
    { name: 'Uttara Ashadha',   lord: 0, deity: 'Vishwadevas' },
    { name: 'Shravana',         lord: 1, deity: 'Vishnu' },
    { name: 'Dhanishtha',       lord: 2, deity: 'Eight Vasus' },
    { name: 'Shatabhisha',      lord: 7, deity: 'Varuna' },
    { name: 'Purva Bhadrapada', lord: 4, deity: 'Aja Ekapada' },
    { name: 'Uttara Bhadrapada',lord: 6, deity: 'Ahir Budhnya' },
    { name: 'Revati',           lord: 3, deity: 'Pushan' },
  ],

  dashaOrder: [8, 5, 0, 1, 2, 7, 4, 6, 3], // Ketu, Venus, Sun, Moon, Mars, Rahu, Jupiter, Saturn, Mercury

  yogas: [
    { name: 'Raj Yoga',       desc: 'Lords of Kendra and Trikona houses are conjunct or in mutual aspect. Indicates power, leadership, name, fame, and high authority in career and society.',  remedy: 'Worship Lord Vishnu on Thursdays. Offer yellow flowers and turmeric.' },
    { name: 'Gaja Kesari',    desc: 'Jupiter is placed in a Kendra (1st, 4th, 7th, 10th) from the Moon. Bestows fame, intelligence, eloquence, wealth, and noble qualities like an elephant-lion.',  remedy: 'Feed bananas to cows on Thursdays. Chant Guru Beej mantra daily.' },
    { name: 'Dhana Yoga',     desc: '2nd and 11th house lords are connected, or Jupiter occupies the 2nd/11th house. Indicates financial prosperity, accumulated wealth, and material abundance.',  remedy: 'Chant Sri Lakshmi Sahasranama. Donate yellow items on Thursdays.' },
    { name: 'Budhaditya',     desc: 'Sun and Mercury are conjunct in the same house. Blesses the native with sharp intellect, excellent communication, and skill in arts, sciences, and administration.',  remedy: 'Offer red flowers to the rising Sun on Sundays. Practice Surya Namaskar.' },
    { name: 'Chandra-Mangal', desc: 'Moon and Mars are conjunct or in mutual aspect. Indicates wealth accumulation through business, real estate, trade, and boldness in financial ventures.',  remedy: 'Offer red cloth to Lord Hanuman on Tuesdays. Chant Hanuman Chalisa.' },
    { name: 'Viparita Raja',  desc: 'Lords of 6th, 8th, or 12th houses occupy each other\'s houses. Indicates rise from adversity, success through unusual means, and triumph over challenges.',  remedy: 'Fast on Saturdays. Donate to those in need on the day of the relevant lord.' },
    { name: 'Neecha Bhanga',  desc: 'A debilitated planet receives cancellation of its debility. Indicates tremendous resilience, rise after great struggle, and eventual mastery over challenges.',  remedy: 'Worship the deity of the planet whose debility is cancelled with devotion.' },
    { name: 'Parijata',       desc: 'The dispositor of the Lagna lord is placed in its own sign or exaltation. Indicates luxury, high social respect, royal comforts, and recognition from authorities.',  remedy: 'Light sesame oil lamps on Saturdays. Offer prayers to Lord Shiva and Vishnu.' },
  ],

  doshas: [
    { name: 'Mangal Dosha',    desc: 'Mars occupies the 1st, 4th, 7th, 8th, or 12th house from Lagna, Moon, or Venus. Can cause delays, turbulence, or separation in marriage and partnerships.',    remedy: 'Worship Lord Hanuman on Tuesdays. Consider Kumbh Vivah. Wear coral after expert consultation.' },
    { name: 'Kaal Sarp Dosha', desc: 'All seven planets (Sun through Saturn) are hemmed between Rahu and Ketu. Causes intense karmic challenges, obstacles, vivid dreams, and periods of struggle.',    remedy: 'Perform Kaal Sarp puja at Trimbakeshwar, Ujjain, or Nasik. Chant Rahu-Ketu mantra daily.' },
    { name: 'Pitru Dosha',     desc: 'Affliction of the 9th house, Sun, or Moon, or malefic planets placed there. Indicates ancestral karmic debt that requires proactive rituals to resolve and heal.',    remedy: 'Perform Shraddha on Amavasya. Offer water (tarpan) to ancestors. Feed Brahmins on the anniversary of parents\' passing.' },
    { name: 'Shani Sade-Sati', desc: 'Saturn transits through the 12th, 1st, and 2nd houses from the natal Moon sign — a 7.5-year period. Brings tests, discipline, hard lessons, and profound transformation.',    remedy: 'Feed crows, dogs, and the poor on Saturdays. Chant Shani mantra 23,000 times. Light sesame oil lamp.' },
  ],

  divisionalCharts: [
    { code: 'D-1',  name: 'Rashi',           full: 'Natal / Birth Chart',     desc: 'The primary chart governing overall life, body, personality, and all major events.' },
    { code: 'D-2',  name: 'Hora',            full: 'Wealth Chart',            desc: 'Financial prosperity, monetary resources, and wealth accumulation.' },
    { code: 'D-9',  name: 'Navamsha',        full: 'Soul & Marriage',         desc: 'Most important divisional — reveals marriage karma, dharma, inner soul nature.' },
    { code: 'D-10', name: 'Dashamsha',       full: 'Career & Profession',     desc: 'Professional achievements, status, contribution to society.' },
    { code: 'D-7',  name: 'Saptamsha',       full: 'Children Chart',          desc: 'Children, fertility, relationship with progeny.' },
    { code: 'D-4',  name: 'Chaturthamsha',   full: 'Property Chart',          desc: 'Fixed assets, property, ancestral heritage.' },
    { code: 'D-16', name: 'Shodashamsha',    full: 'Vehicles & Comforts',     desc: 'Vehicles, material happiness, comforts of life.' },
    { code: 'D-20', name: 'Vimshamsha',      full: 'Spiritual Progress',      desc: 'Spiritual practice, upasana, path to liberation.' },
    { code: 'D-60', name: 'Shashtiamsha',    full: 'Past Karma Chart',        desc: 'Ultimate karmic record; past-life influences and soul evolution.' },
  ],

  mantras: [
    { planet: 'Sun',     text: 'ॐ घृणि सूर्य आदित्य श्रीं',         roman: 'Om Ghrani Surya Aditya Shrim',                     meaning: 'I bow to the radiant Sun, source of all light and life energy.',      count: 7000,   day: 'Sunday',    color: 'Red', metal: 'Gold' },
    { planet: 'Moon',    text: 'ॐ सोम सोमाय नमः',                    roman: 'Om Som Somaya Namah',                               meaning: 'Salutations to the Moon, the nourisher of all life with cool light.',  count: 11000,  day: 'Monday',    color: 'White', metal: 'Silver' },
    { planet: 'Mars',    text: 'ॐ क्रां क्रीं क्रौं सः भौमाय नमः',  roman: 'Om Kram Krim Kraum Sah Bhaumaya Namah',            meaning: 'Salutations to Mars, the brave planet of courage and vitality.',       count: 7000,   day: 'Tuesday',   color: 'Red', metal: 'Copper' },
    { planet: 'Mercury', text: 'ॐ बुं बुधाय नमः',                    roman: 'Om Bum Budhaya Namah',                              meaning: 'Salutations to Mercury, swift planet of intelligence and trade.',       count: 17000,  day: 'Wednesday', color: 'Green', metal: 'Bronze' },
    { planet: 'Jupiter', text: 'ॐ ग्रां ग्रीं ग्रौं सः गुरवे नमः', roman: 'Om Gram Grim Graum Sah Gurave Namah',              meaning: 'Salutations to Jupiter, the great teacher and bestower of wisdom.',     count: 19000,  day: 'Thursday',  color: 'Yellow', metal: 'Gold' },
    { planet: 'Venus',   text: 'ॐ द्रां द्रीं द्रौं सः शुक्राय नमः',roman: 'Om Dram Drim Draum Sah Shukraya Namah',            meaning: 'Salutations to Venus, planet of love, beauty, and abundance.',         count: 16000,  day: 'Friday',    color: 'White/Pink', metal: 'Silver' },
    { planet: 'Saturn',  text: 'ॐ प्रां प्रीं प्रौं सः शनैश्चराय नमः', roman: 'Om Pram Prim Praum Sah Shanaischaraya Namah',  meaning: 'Salutations to Saturn, the just lord of karma and discipline.',        count: 19000,  day: 'Saturday',  color: 'Blue/Black', metal: 'Iron' },
    { planet: 'Rahu',    text: 'ॐ भ्रां भ्रीं भ्रौं सः राहवे नमः', roman: 'Om Bhram Bhrim Bhraum Sah Rahave Namah',           meaning: 'Salutations to Rahu, shadow node of ambition and transformation.',      count: 18000,  day: 'Saturday',  color: 'Blue', metal: 'Lead' },
    { planet: 'Ketu',    text: 'ॐ स्त्रां स्त्रीं स्त्रौं सः केतवे नमः', roman: 'Om Stram Strim Straum Sah Ketave Namah',    meaning: 'Salutations to Ketu, node of liberation, detachment, and spirituality.',count: 7000,   day: 'Tuesday',   color: 'Brown/Grey', metal: 'Iron' },
  ],

  remedies: {
    Sun:     ['Offer water mixed with red flowers to the rising Sun while chanting "Om Suryaya Namah" 12 times', 'Wear ruby (Manik) in gold on the ring finger of the right hand on a Sunday morning', 'Fast on Sundays — consume only one meal at noon, preferably wheat preparations', 'Chant Gayatri Mantra (Om Bhur Bhuva Svaha...) 108 times at sunrise daily', 'Feed wheat bread or jaggery to cows and birds on Sundays', 'Wear copper bracelet on the right wrist', 'Donate red cloth, wheat, copper, or jaggery to a learned person on Sundays'],
    Moon:    ['Offer raw milk, white flowers, or rice to Lord Shiva on Mondays', 'Wear pearl (Moti) set in silver on the little finger of the right hand on a Monday', 'Consume white foods — rice, milk, yogurt, white sesame on Mondays', 'Meditate facing north on full moon nights for 20–40 minutes', 'Donate white cloth, rice, or silver to women or mothers in need', 'Keep a small Shiva lingam at home; offer milk every Monday', 'Practice moon gazing (Trataka) on the full moon'],
    Mars:    ['Offer red flowers, red sindoor, and red cloth to Lord Hanuman on Tuesdays', 'Wear red coral (Moonga) set in gold or copper on the ring finger on a Tuesday', 'Fast on Tuesdays — eat only sattvic, vegetarian food once', 'Chant Hanuman Chalisa 7 times on Tuesdays for protection and courage', 'Donate red lentils (masoor dal), jaggery, or copper on Tuesdays', 'Plant red flowering trees or shrubs in your home garden', 'Serve police, military, or fire service personnel as an act of Mars gratitude'],
    Mercury: ['Feed green fodder or spinach to cows on Wednesdays', 'Wear emerald (Panna) set in gold on the little finger on a Wednesday morning', 'Read sacred or educational texts daily — practice calligraphy or study', 'Donate green vegetables, moong dal (green lentils), or books on Wednesdays', 'Visit a Vishnu temple and offer Tulsi leaves while chanting Vishnu Sahasranama', 'Keep a small green plant (Tulsi or money plant) on your study desk', 'Speak mindfully and truthfully — avoid gossip, lies, or harsh speech'],
    Jupiter: ['Feed cows with yellow items — turmeric balls, banana, yellow sweet on Thursdays', 'Wear yellow sapphire (Pukhraj) set in gold on the index finger on a Thursday', 'Fast on Thursdays — eat only yellow foods (dal, banana, turmeric rice) once', 'Donate yellow cloth, turmeric, chickpeas, or gold to a Brahmin or teacher', 'Sit under a peepal tree and meditate or chant on Thursdays at sunrise', 'Respect teachers, gurus, elders, and parents — touch their feet', 'Worship Lord Vishnu or Dakshinamurthy on Thursdays with yellow flowers'],
    Venus:   ['Offer white flowers, rice, and sugar to Goddess Lakshmi on Fridays', 'Wear diamond or white sapphire set in gold on the middle finger on a Friday', 'Practice music, art, dance, or creative expression for spiritual growth', 'Donate white cloth, sugar, white sesame, perfume, or white sweets on Fridays', 'Keep your home, workspace, and personal appearance clean, beautiful, and fragrant', 'Light rose or jasmine incense daily — maintain aesthetic surroundings', 'Practice kindness, generosity, and appreciation of beauty in all forms'],
    Saturn:  ['Feed crows, dogs, ants, and the homeless on Saturdays', 'Wear blue sapphire (Neelam) ONLY after consultation with an experienced astrologer', 'Light a sesame oil (til ka tel) lamp under a peepal tree on Saturday evenings', 'Donate iron utensils, black sesame seeds, black cloth, or mustard oil on Saturdays', 'Practice selfless service (seva) — volunteer at hospitals, shelters, or old age homes', 'Recite Shani Stotra or Shani mantra 108 times every Saturday', 'Respect laborers, servants, the elderly, and the marginalized in daily life'],
    Rahu:    ['Donate blankets, sesame seeds, or coal to the poor on Saturdays or Sundays', 'Keep a whole coconut at the entrance of your home; replace it monthly on a Saturday', 'Feed street dogs, crows, and homeless people regularly on weekends', 'Meditate regularly — especially during Rahu Kaal (1.5 hours before sunset on Saturdays)', 'Wear hessonite garnet (Gomed) set in silver on the middle finger after expert consultation', 'Avoid alcohol, non-vegetarian food on Saturdays; maintain cleanliness of home', 'Chant "Om Raam Rahave Namah" 108 times daily at dusk'],
    Ketu:    ['Feed dogs daily — Ketu rules dogs and they carry Ketu karma', 'Take care of stray, abandoned, or old animals — this directly pacifies Ketu', 'Worship Lord Ganesha and Lord Bhairava on Tuesdays and Saturdays', 'Donate grey or dark brown cloth, blankets, or sesame to the poor on Tuesdays', 'Practice deep meditation, yoga nidra, or past-life regression for Ketu healing', 'Wear cat\'s eye (Lehsunia) set in silver on the middle finger after qualified consultation', 'Visit and serve at ashrams, cremation grounds, or spiritual centers'],
  },

  weekdays: ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
  months:   ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],

  tithis:   ['Pratipada', 'Dvitiya', 'Tritiya', 'Chaturthi', 'Panchami', 'Shashthi', 'Saptami', 'Ashtami', 'Navami', 'Dashami', 'Ekadashi', 'Dvadashi', 'Trayodashi', 'Chaturdashi', 'Purnima', 'Pratipada', 'Dvitiya', 'Tritiya', 'Chaturthi', 'Panchami', 'Shashthi', 'Saptami', 'Ashtami', 'Navami', 'Dashami', 'Ekadashi', 'Dvadashi', 'Trayodashi', 'Chaturdashi', 'Amavasya'],
  yogaNames:['Vishkambha','Priti','Ayushman','Saubhagya','Shobhana','Atiganda','Sukarma','Dhriti','Shula','Ganda','Vriddhi','Dhruva','Vyaghata','Harshana','Vajra','Siddhi','Vyatipata','Variyan','Parigha','Shiva','Siddha','Sadhya','Shubha','Shukla','Brahma','Indra','Vaidhriti'],
  karanas:  ['Bava','Balava','Kaulava','Taitila','Garaja','Vanija','Vishti','Shakuni','Chatushpada','Nagava','Kimstughna'],

  lifePhases: [
    { icon: '🌱', title: 'Foundation Phase',        years: '0–25',  theme: 'Discovery & Learning' },
    { icon: '🔥', title: 'Action & Ambition Phase', years: '25–42', theme: 'Career & Relationships' },
    { icon: '🌟', title: 'Mastery & Harvest Phase', years: '42–60', theme: 'Authority & Wisdom' },
    { icon: '🕊️', title: 'Wisdom & Renunciation',  years: '60–75', theme: 'Legacy & Spirituality' },
    { icon: '🌅', title: 'Liberation & Moksha',     years: '75+',   theme: 'Return to Source' },
  ],

  compatibleSigns: {
    Aries:       ['Leo', 'Sagittarius', 'Gemini', 'Aquarius'],
    Taurus:      ['Virgo', 'Capricorn', 'Cancer', 'Pisces'],
    Gemini:      ['Libra', 'Aquarius', 'Aries', 'Leo'],
    Cancer:      ['Scorpio', 'Pisces', 'Taurus', 'Virgo'],
    Leo:         ['Aries', 'Sagittarius', 'Gemini', 'Libra'],
    Virgo:       ['Taurus', 'Capricorn', 'Cancer', 'Scorpio'],
    Libra:       ['Gemini', 'Aquarius', 'Leo', 'Sagittarius'],
    Scorpio:     ['Cancer', 'Pisces', 'Virgo', 'Capricorn'],
    Sagittarius: ['Aries', 'Leo', 'Libra', 'Aquarius'],
    Capricorn:   ['Taurus', 'Virgo', 'Scorpio', 'Pisces'],
    Aquarius:    ['Gemini', 'Libra', 'Aries', 'Sagittarius'],
    Pisces:      ['Cancer', 'Scorpio', 'Taurus', 'Capricorn'],
  },

  predictionTexts: {
    daily: {
      general: [
        'Today the cosmic energies favor <em>new beginnings</em>. Your lagna lord supports bold decisions aligned with your dharma. Act before noon for best outcomes.',
        'A day for <em>introspection and planning</em> rather than outward action. Review ongoing projects, process emotions before proceeding.',
        'Excellent day for <em>communication and networking</em>. Mercury energizes — reach out, write, present ideas confidently.',
        'Saturn calls for <em>patience and discipline</em> today. Steady, quality work brings lasting rewards. Avoid shortcuts.',
        'Jupiter brings an <em>unexpected opportunity</em> today. Stay open to wisdom from an elder or learned person.',
        'Venus blesses <em>creativity and relationships</em>. A social gathering or creative project brings joy and connection.',
        'Mars energizes your <em>physical vitality</em>. Channel it into exercise or ambitious projects. Guard against impulsiveness.',
        'Rahu creates <em>heightened intuition</em> today. Dreams carry meaning. Stay grounded and avoid illusions.',
      ],
      health: [
        'Your energy is <em>high and sustained</em>. Ideal time to exercise, practice yoga, or begin a new wellness routine.',
        'Be mindful of <em>digestive health</em>. Warm foods, herbal teas, and gentle walks support your system today.',
        'Mental wellness needs priority — practice <em>pranayama and deep breathing</em>. Limit screen time after evening.',
        'Good day for <em>healing and recovery</em>. Rest, herbal remedies, and light sattvic food restore vitality effectively.',
        'Your body is asking for <em>movement and fresh air</em>. A 30-minute walk outside significantly boosts your mood and health.',
        'Energy may feel <em>lower than usual</em> — honor this by resting, eating nourishing foods, and sleeping earlier tonight.',
      ],
      career: [
        'A <em>productive and focused</em> work day. Tackle challenging tasks in the morning when mental clarity peaks.',
        '<em>Collaboration with a colleague</em> leads to a breakthrough today. Share your ideas openly without hesitation.',
        'Avoid major decisions about career before 3 PM today. <em>Review and analyze</em> before committing to any direction.',
        'A <em>recognition or reward</em> for past effort may arrive today. Your consistent work is being noticed by authorities.',
        '<em>Creative problem-solving</em> is your superpower today. Think outside established frameworks for best solutions.',
        'A challenging interaction at work resolves with <em>calm, diplomatic communication</em>. Choose patience over reaction.',
      ],
      finance: [
        'Hold off on <em>major financial decisions</em> today. Review and double-check all numbers and contracts carefully.',
        'An <em>unexpected financial opportunity</em> may arise. A delayed payment or promised sum could arrive today.',
        'Good day for <em>financial planning</em>. Saturn supports structured, long-term financial decisions and savings.',
        'Venus supports a <em>practical, joyful purchase</em>. A considered buy for the home or a gift brings lasting happiness.',
        '<em>Review your budget</em> and identify areas of unnecessary expenditure. Small adjustments create long-term gains.',
        'A discussion about money with a partner or family member goes <em>smoothly and productively</em> today.',
      ],
      love: [
        'Atmosphere in your <em>relationship is warm and harmonious</em>. Small gestures of love go far today.',
        'Clear, <em>honest communication</em> resolves a past misunderstanding. Choose openness over guardedness.',
        'Today calls for <em>self-love and personal space</em>. Nurture yourself fully before giving to others.',
        'Romance is <em>elevated and dreamy</em> under Venus. Plan something meaningful — even a simple, shared meal.',
        'A <em>new connection</em> is possible through shared interests or creative circles for those who are single.',
        'Deep <em>emotional sharing</em> with your partner creates profound intimacy. Be vulnerable and present.',
      ],
    },
    monthly: {
      career: [
        'Strong professional advancement this month. Your diligence is noticed by those in authority. A promotion or recognition is possible in the second half.',
        'Challenges in the professional sphere require creative problem-solving. Use setbacks as information. A clearer path emerges by month\'s end.',
        'New opportunities arise, but they require bold initiative. Step outside your comfort zone — discomfort is temporary, growth is permanent.',
        'A powerful collaboration begins this month that will significantly shape your professional trajectory for the next year.',
      ],
      wealth: [
        'Income is steady this month, and a potential bonus or windfall is indicated after the 15th. Invest conservatively; avoid speculative ventures.',
        'Tighten your budget and prioritize financial security. Unexpected expenses may arise — having a cushion brings peace of mind.',
        'Financial dealings require extra caution. Read all agreements carefully. A trusted advisor\'s input is valuable before major decisions.',
        'An unexpected financial gain arrives through a family connection or past investment. Gratitude amplifies the flow of abundance.',
      ],
      love: [
        'Harmony in personal relationships is highlighted. Shared experiences deepen bonds. Singles find meaningful connection through work or shared interests.',
        'Communication with a loved one requires extra patience this month. Practice deep listening — what is left unsaid holds more truth.',
        'Romantic energy peaks mid-month. Plan something meaningful with your partner. Singles: the new moon brings new possibilities.',
        'A relationship that felt stagnant finds renewed depth and passion this month. Honest vulnerability is the key that unlocks it.',
      ],
      health: [
        'Your vitality is robust this month. Ideal time to begin a new fitness routine, dietary change, or wellness practice.',
        'Stress management is the priority. Pranayama, long walks, and early bedtime support your nervous system. Say no to over-commitment.',
        'A minor health concern needs early attention — address it proactively rather than waiting. Prevention is your wisest strategy.',
        'Energy fluctuates this month due to planetary transitions. Regular meals, consistent sleep, and moderate exercise are your anchors.',
      ],
      spiritual: [
        'Spiritual receptivity is exceptionally high. Dreams and synchronicities arrive with meaningful messages. Begin a meditation journal.',
        'The universe prompts a deeper inquiry into life\'s purpose. Long walks, silence, and the company of wise people bring revelation.',
        'A karmic cycle completes this month. Release what no longer serves — beliefs, patterns, relationships. Space invites something new.',
        'A significant spiritual encounter — a book, a teacher, a moment of stillness — reshapes your understanding of yourself and the cosmos.',
      ],
    },
    yearly: {
      themes: [
        'A Year of Transformation & New Identity',
        'A Year of Building Solid Foundations',
        'A Year of Expansion, Travel & Learning',
        'A Year of Relationships & Inner Balance',
        'A Year of Inner Power & Deep Truth',
        'A Year of Achievement & Public Recognition',
        'A Year of Spiritual Renewal & Release',
        'A Year of Creative Abundance',
        'A Year of Completion & Karmic Closure',
      ],
      quarters: [
        { q: 'Q1 (Jan–Mar)', theme: 'Launch & Plant',        desc: 'The year opens with strong momentum. New projects, career moves, and personal intentions set now carry powerful seed energy through the rest of the year.' },
        { q: 'Q2 (Apr–Jun)', theme: 'Grow & Expand',         desc: 'Venus and Mercury collaborate to bring communication, relationship depth, and financial growth. Travel and learning opportunities arise naturally.' },
        { q: 'Q3 (Jul–Sep)', theme: 'Harvest & Test',        desc: 'Saturn\'s influence brings challenges that refine and strengthen. Those who have put in genuine effort see recognition. Stay consistent through the pressure.' },
        { q: 'Q4 (Oct–Dec)', theme: 'Complete & Consolidate',desc: 'Closures, completions, and celebrations mark the final quarter. The groundwork for next year\'s cycle begins forming in December.' },
      ],
      monthTexts: [
        'Powerful new beginnings. Set intentions with clarity and act decisively in the first two weeks.',
        'Steady financial focus. A resource or income opportunity reveals itself through patient attention.',
        'Ideas flow freely. Express, communicate, and connect — collaboration brings unexpected breakthroughs.',
        'Home and family dynamics shift. An important domestic conversation or decision moves things forward.',
        'Creative peak — artistic, romantic, and educational pursuits thrive. Risk bold self-expression now.',
        'Health and service come to the foreground. Establish a sustainable wellness routine this month.',
        'Relationship dynamics deepen. An honest heart-to-heart reshapes a key relationship for the better.',
        'A transformative shift in how you see yourself arrives. Embrace the evolution; release the old identity.',
        'Fortune smiles widely. Luck, travel, higher learning, and synchronistic meetings mark this month.',
        'Career achievements are recognized and celebrated. Your authority and expertise draw opportunities.',
        'Unexpected gains, financial and social, arrive through your network. Give generously — it amplifies returns.',
        'Reflection, rest, and spiritual depth close the year. The insights gathered now seed the coming cycle.',
      ],
    },
    life: {
      phases: [
        ['The early years are shaped by the ascendant lord and the 4th house. Home, mother, and foundational education become the bedrock of your entire life journey.', 'Your Moon sign reveals the emotional conditioning of childhood. Benefic planets here gift a nurturing upbringing; malefic ones build resilience through challenge.', 'Mercury\'s position describes the nature of your early intellect and learning style. The world of ideas, curiosity, and school life are powerfully shaped by its placement.'],
        ['This is the period of maximum worldly engagement. Your 10th house karma unfolds — career rises, status is established, and the dharma of your profession becomes clear.', 'Marriage and partnerships (7th house) come alive in this phase. Venus\'s position determines the quality, timing, and nature of your primary relationship.', 'Saturn\'s influence tests patience and commitment, but each test passed leads to lasting achievement and an unshakeable inner foundation.'],
        ['The efforts of previous decades begin bearing fruit. The 9th house of fortune and 11th house of gains become prominently active and rewarding.', 'This is when wisdom transforms into leadership. Your Jupiter placement shows the domain in which you naturally become a teacher, mentor, or authority.', 'Health needs conscious attention, particularly the areas ruled by your 6th and 8th house lords. Ayurvedic practices aligned with your lagna element are deeply beneficial.'],
        ['The 9th and 12th houses activate strongly — drawing you toward pilgrimage, philosophy, legacy, and the deeper questions of existence.', 'This phase brings a natural turning toward spiritual practice. Your Ketu placement reveals past-life gifts that re-emerge in full power now.', 'Family bonds deepen. Grandchildren often reflect your own karmic traits. Your accumulated wisdom becomes the true treasure most sought by those around you.'],
        ['The final chapter is dominated by 12th house energy — release, surrender, and preparation for the next great journey of the soul.', 'Saturn and Ketu\'s influence grows, dissolving attachments. Spiritual practices and good karma accumulated over a lifetime become the ultimate wealth.', 'The Navamsha (D-9) chart reveals the soul\'s deepest nature — in this phase, the outer and inner self finally merge into wholeness and peace.'],
      ],
    },
  },
};
